### ISSUE TITLE
Exe file is not running

### ISSUE THREAD

**Issue by shadez15** [sileshn/EndeavourOSWSL2#1]
I tried to launch EndeavourOS.exe, but it terminates within a second. Any help will be appreciated.

**Comment by sileshn** [comment]
Not helpful. Need more information on your setup. Have you completed all prerequisite steps? Check the readme.

**Comment by shadez15** [comment]
yes I did all prerequisite steps. When I launched the exe file for the first time it installed, but I am running it again to access the os it terminates within a second.

**Comment by sileshn** [comment]
Which windows version? I am not sure how I can help without knowing the exact error. Also if you are running beta Or dev builds, I can't help. I have been using eoswsl2 on windows 10 for a couple of months without issues.

**Comment by shadez15** [comment]
Version 21h2(build 1904.1826). I cant recognize the problem. I tried ArchWSL ,it worked fine but nowhere with this one.

**Comment by shadez15** [comment]
It is working now I removed the registration and reinstalled it. Thank you for your time.
