### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by kaltec-w** [sileshn/EndeavourOSWSL2#10]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.19045.4355]

### Kernel Version

Default Version: 2

### Repro Steps

- download the release (tried both most recent and 1 version back)
- extract to c:\wsl
- run endeavouros.exe

### Expected Behavior

EOS to be installed

### Actual Behavior

```
Using: C:\wsl\rootfs.tar.gz
Installing...
ERR: Unspecified error
HRESULT: 0x80004005
Press enter to exit...
```

**Comment by sileshn** [comment]
There can be many reasons. Try updating wsl with 'wsl --update' command.

https://github.com/microsoft/WSL/issues?q=0x80004005

**Comment by kaltec-w** [comment]
I found that thread and worked through some of the suggestions but was not able to get it working. I ended up switching to the ArchWSL by yuk7, and (after allow-listing the application due to a false-positive with windows defender) successfully installed that version instead.

**Comment by sileshn** [comment]
Not sure whats going on. I can install and run just fine. Closing the issue since you have moved on to another distro.


https://github.com/sileshn/EndeavourOSWSL2/assets/977360/011cf27e-e783-4b18-a63a-ff301d42149e
