### ISSUE TITLE
Systemd setup

### ISSUE THREAD

**Issue by TimoKramer** [sileshn/EndeavourOSWSL2#2]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.19045.2604]

### Kernel Version

5.15.79.1-microsoft-standard-WSL2

### Repro Steps

- setting .wslconfig in `/mnt/c/Users/Timo/.wslconfig`
- restarting wsl with `wsl.exe --shutdown`
- `sudo systemctl start docker`

### Expected Behavior

It should start docker daemon

### Actual Behavior

Failed to connect to bus: Connection refused

Tried some other things:
```
sudo systemctl  list-units                                                                       
Failed to connect to bus: Connection refused

sudo systemctl --user list-units                                                                   
Failed to connect to bus: No medium found

systemctl --user list-units                                                                      
Failed to list units: Process org.freedesktop.systemd1 exited with status 1

systemctl list-units                                                                              
Failed to connect to bus: Connection refused

systemctl --user status podman                                                                     
Failed to get properties: Process org.freedesktop.systemd1 exited with status 1
```

Can you tell me if this is something related to your distro? (awsome work by the way) Or is it some configuration issue on linux?

Help is highly appreciated. Thanks and keep up the good work!

**Comment by TimoKramer** [comment]
ok, now I got it... it wasn't running systemd because you have to set the boot-config in the `/etc/wsl.conf` in the distro. not globally.

**Comment by sileshn** [comment]
FYI,

If you are running the latest release, systemd is setup automatically based on the windows version you are running. Nothing needs to be done from the users end.
