### ISSUE TITLE
can't install package 

### ISSUE THREAD

**Issue by ryannewcomer** [sileshn/EndeavourOSWSL2#6]
### Requirements

- [X] Yes
- [ ] No

### WSL Version

- [X] WSL 2
- [ ] WSL 1

### Version

Microsoft Windows [Version 10.0.22621.1992]

### Kernel Version

5.15.90.1-microsoft-standard-WSL2

### Repro Steps

sudo pacman -S xorg-xwininfo
![image](https://github.com/sileshn/EndeavourOSWSL2/assets/88273136/a5711ce8-4db9-42d3-ac40-0a0383fe8b54)
i had try to found the wslutilities, but i can't found it

### Expected Behavior

of cause install xwininfo!!

### Actual Behavior

![image](https://github.com/sileshn/EndeavourOSWSL2/assets/88273136/f30fa023-eae0-4915-9684-0efd9f660c89)

**Comment by sileshn** [comment]
https://github.com/wslutilities/wslu/issues/278#issuecomment-1589870056

**Comment by ryannewcomer** [comment]
thinks!!
