### ISSUE TITLE
Add GUI Support, It is easily implementable with VcXsrv 

### ISSUE THREAD

**Issue by 0x0OZ** [sileshn/EndeavourOSWSL2#7]
### Requirements

- [ ] Yes
- [ ] No

### WSL Version

- [ ] WSL 2
- [ ] WSL 1

### Version

----

### Kernel Version

----

### Repro Steps

I have seen Kali Linux on WSL support GUI through VNC.

Kali Linux has a tool called `kex` which was added in one of 2020 releases, This win-kex tool somehow (I haven't checked how it works yet) runs TigerVNC and connects it to Kali environment 
https://www.kali.org/docs/wsl/win-kex-sl/
And here is the utility:
https://sourceforge.net/projects/vcxsrv/

### Expected Behavior

--

### Actual Behavior

--

**Comment by sileshn** [comment]
Nope. Its up to the user to add support.

**Comment by thomas725** [comment]
should the guide you have for Manjaro also work for EndeavourOS?
https://github.com/sileshn/ManjaroWSL2?tab=readme-ov-file#how-to-setup-a-desktop-environment

**Comment by sileshn** [comment]
It should.

**Comment by thomas725** [comment]
Since Microsoft nowadays already includes "archlinux" into WSL2 directly I've used that, and your guide linked above worked fine there too! Thank you! ❤ 

ps.: see also: https://wiki.archlinux.org/title/Install_Arch_Linux_on_WSL
